#!/bin/sh
# from http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=build/* --exclude=node_modules/* --exclude=*/*.min.js --languages=JavaScript
mv .git/tags.$$ .git/tags
