# Config for the tmux 3.6 era

# Use Ctrl-a as leader
unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g mouse off
set -g default-terminal "screen-256color"
set -g history-limit 100000
set -g monitor-activity on

# 1 based numbering (Left-hand priority typing)
set -g base-index 1
setw -g pane-base-index 1

setw -g pane-border-indicators both
set -g -p allow-set-title on

set -g mode-keys vi
set -g status-keys vi

#
# Bindings
#

bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

bind S command-prompt { new-session -s "%%" }

# tree-picker, -Z for full-width
bind t choose-tree -Z -O activity

bind a last-window # Bounce to switch
bind C-a last-window # Bounce to switch
# leave last-pane as default o -- opposing pinky!

#TODO: p = print screen (visible area), something like: 
#bind p capture-pane -J
#bind P capture-pane -S- -E- -J -e 

bind R source-file ~/.config/tmux/tmux.conf

bind * list-clients

bind C-s command-prompt { rename-session "%%" }
bind r command-prompt { rename-window "%%" }

#
# Status Bar
#

set -g status-bg '#333333'
set -g status-fg brightwhite
set -g status-justify left
set -g status-left-length 32 
set -g status-right-length 80

# if   or   don't render, get yourself a Nerd Font ASAP. E.g. https://github.com/githubnext/monaspace "Monaspace Neon NF"

set -g status-left '#[fg=black,bg=red][tmux:#S]#[fg=red,bg=#333333] '
set -g status-right '#[fg=red,bg=#333333]#[fg=black,bg=red][#T][#h]'

set -g window-status-format '#[fg=grey]#[fg=black,bg=grey]#I#D #W #F#[fg=grey,bg=#333333]'
set -g window-status-current-format '#[fg=blue,bold]#[fg=#ffffff,bg=blue]#I#D #[fg=black]#W #F#[fg=blue,bg=#333333]'
